import React, { useEffect, useRef, useState } from 'react';
import { content as c, type Project } from './content';
import './style.css';
import './motion.css';
import { useStudioMotion } from './useStudioMotion';
import { LemonDrop } from './LemonDrop';
const Arrow=()=><span aria-hidden="true">↗</span>;
const mail=`mailto:${c.contact.email}?subject=${encodeURIComponent(c.ui.enquirySubject)}`;
function Brand(){return <a className="brand" href="#home" aria-label={`${c.brand.name} ${c.brand.descriptor} — ${c.nav[0][0]}`}><img src={c.brand.logo} alt="" width="48" height="48"/><span><strong>{c.brand.name}</strong><small>{c.brand.descriptor}</small></span></a>}
function Heading({label,title,italic}:{label:string;title:string;italic:string}){return <><p className="eyebrow">{label}</p><h2>{title}<br/><em>{italic}</em></h2></>}
function ProjectView({project,onClose}:{project:Project|null;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=dialog.current;if(project){d?.showModal();document.body.style.overflow='hidden'}return()=>{d?.close();document.body.style.overflow=''}},[project]);
 return <dialog ref={dialog} className="project-dialog" aria-labelledby="project-title" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}>{project&&<div className="dialog-inner"><button className="dialog-close" onClick={onClose} autoFocus aria-label={c.ui.close}>×</button><p className="eyebrow">{project.category}</p><h2 id="project-title">{project.name}</h2><p className="dialog-summary">{project.summary}</p><div className="detail-grid"><section><h3>{c.ui.context}</h3><p>{project.context}</p></section><section><h3>{c.ui.role}</h3><p>{project.role}</p></section></div><h3>{c.ui.approach}</h3><ul>{project.approach.map(t=><li key={t}>{t}</li>)}</ul>{project.outcomes.length>0&&<><h3>{c.ui.outcomes}</h3><div className="outcomes">{project.outcomes.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><p className="fine">{c.ui.source}</p></>}<p>{project.note}</p>{project.links.map(link=><a key={link.href} className="text-link" href={link.href} target="_blank" rel="noreferrer">{link.label} <Arrow/></a>)}<button className="button dark mt-8" onClick={onClose}>{c.ui.back}<span aria-hidden="true">↙</span></button></div>}</dialog>
}
function App(){useStudioMotion();const[menu,setMenu]=useState(false);const[project,setProject]=useState<Project|null>(null);
 useEffect(()=>{if(!menu)return;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);document.getElementById('menu-toggle')?.focus()}};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[menu]);
 return <><LemonDrop/><a className="skip" href="#main">{c.ui.skip}</a><header><div className="nav-wrap"><Brand/><nav aria-label="Main navigation" id="navigation" className={menu?'open':''}>{c.nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a href="#contact" className="nav-cta">{c.ui.talk}<Arrow/></a><button id="menu-toggle" className="menu-toggle" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?c.ui.close:c.ui.menu}<span aria-hidden="true">{menu?'−':'+'}</span></button></div></header>
 <main id="main"><section className="hero" id="home"><div className="hero-content"><p className="eyebrow"><span className="tiny-star" aria-hidden="true">✦</span>{c.hero.eyebrow}</p><h1><span className="hero-line hero-line-one">{c.hero.line1}</span><br/><span className="hero-line hero-line-two">{c.hero.line2}</span><br/><em className="hero-line hero-line-three">{c.hero.line3}</em></h1><p className="hero-description">{c.hero.description}</p><div className="hero-actions"><a className="button dark" href="#contact">{c.hero.primary}<Arrow/></a><a className="text-link" href="#work">{c.hero.secondary}<span aria-hidden="true">↓</span></a></div></div><div className="hero-art" aria-hidden="true"><span className="orbit-text">CONTENT WITH CHARACTER</span><img src={c.brand.logo} alt="" width="1100" height="1100" fetchPriority="high"/><span className="handwritten">{c.hero.note}</span><span className="art-star">✦</span></div><div className="hero-foot"><span>{c.hero.foot}</span><span>{c.hero.footRight}</span><a href="#about" aria-label={c.nav[1][0]}>↓</a></div></section>
 <section id="about" className="section difference"><div><Heading label={c.about.label} title={c.about.title} italic={c.about.italic}/></div><div className="difference-copy"><p>{c.about.body}</p><ul>{c.about.items.map(t=><li key={t}><span aria-hidden="true">↗</span>{t}</li>)}</ul><p className="handwritten">{c.about.closing}</p></div></section>
 <section className="proof section" aria-label={c.proof.label}><p className="eyebrow">{c.proof.label}</p><div className="proof-grid">{c.proof.items.map(x=><div key={x.value}><strong>{x.value}</strong><h3>{x.label}</h3><p>{x.note}</p></div>)}</div><p className="fine">{c.proof.note}</p></section>
 <section id="services" className="section services"><div className="section-intro"><Heading label={c.services.label} title={c.services.title} italic={c.services.italic}/><p>{c.services.description}</p></div><div className="service-list">{c.services.items.map(([name,line,detail],i)=><article key={name} className="service-row"><span className="number">0{i+1}</span><h3>{name}</h3><div><h4>{line}</h4><p>{detail}</p></div><span className="service-star" aria-hidden="true">✦</span></article>)}</div></section>
 <section id="work" className="section work"><div className="work-heading"><Heading label={c.work.label} title={c.work.title} italic={c.work.italic}/><p>{c.work.description}</p></div><div className="projects">{c.work.projects.map((p,i)=><article className={`project project-${p.theme}`} key={p.id}><button className="project-visual" onClick={()=>setProject(p)} aria-label={`${c.ui.project}: ${p.name}`}><span className="project-top"><span>{p.category}</span><span>0{i+1}</span></span><span className="project-display">{p.display[0]}<br/><em>{p.display[1]}</em></span><span className="project-bottom"><span>{p.stamp}</span><span className="circle-arrow"><Arrow/></span></span>{p.theme==='avishi'&&<img className="project-lemon" src={c.brand.logo} alt="" width="100" height="100" loading="lazy"/>}</button><div className="project-caption"><h3>{p.name}</h3><p>{p.summary}</p></div></article>)}</div></section>
 <section id="team" className="section team"><div className="section-intro"><Heading label={c.team.label} title={c.team.title} italic={c.team.italic}/><p>{c.team.description}</p></div><div className="team-grid">{c.team.people.map(p=><article key={p.name}><div className="team-top"><span className="initials" aria-hidden="true">{p.initials}</span><span className="eyebrow">{p.school}</span></div><h3>{p.name}</h3><p className="role">{p.role}, {c.brand.name} {c.brand.descriptor.toLowerCase()}</p><p>{p.bio}</p><a className="text-link" href={p.href} target="_blank" rel="noreferrer">{p.handle}<Arrow/></a></article>)}</div></section>
 <section className="section process"><Heading label={c.process.label} title={c.process.title} italic={c.process.italic}/><div className="process-grid">{c.process.items.map(([name,desc],i)=><article key={name}><span className="process-number">0{i+1}</span><h3>{name}</h3><p>{desc}</p></article>)}</div></section>
 <section id="contact" className="section contact"><div className="contact-flourish" aria-hidden="true"><img src={c.brand.logo} alt="" width="88" height="88" loading="lazy"/><span>✦</span></div><p className="eyebrow">{c.contact.label}</p><h2>{c.contact.title}<br/><em>{c.contact.italic}</em></h2><p className="handwritten">{c.contact.subtitle}</p><a className="button yellow" href={mail}>{c.contact.cta}<Arrow/></a><p className="contact-note">{c.contact.note}</p><div className="contact-links"><a href={mail}>{c.contact.email}<Arrow/></a><a href={c.contact.whatsapp} target="_blank" rel="noreferrer">{c.contact.whatsappLabel}<Arrow/></a></div></section></main>
 <footer><Brand/><p className="handwritten">{c.brand.tagline}</p><a href="#home">{c.ui.top} ↑</a><div className="footer-bottom"><span>© {new Date().getFullYear()} {c.ui.copyright}</span><span>{c.hero.foot}</span></div></footer><ProjectView project={project} onClose={()=>setProject(null)}/></>
}
export default App;
