// All visitor-facing copy, contact details and project records live here.
// Evidence: supplied offerings.pdf (2026 snapshot) and the user's website brief.
export const content = {
  intro: {
    firstLine: 'when life gives you lemons...',
    secondLine: 'make lemon tea.',
  },
  brand: {
    name: 'Chillchai',
    descriptor: 'CREATIONS',
    tagline: 'when life gives you lemons, make lemon tea.',
    logo: '/assets/logo.webp',
  },
  nav: [
    ['Home', 'home'],
    ['What We Do', 'services'],
    ['About', 'about'],
    ['Our Work', 'work'],
    ['Contact', 'contact'],
  ],
  ui: {
    talk: 'Let’s Talk',
    menu: 'Menu',
    close: 'Close',
    skip: 'Skip to content',
    project: 'Explore the project',
    back: 'Back to all work',
    context: 'The context',
    role: 'Our role',
    approach: 'The approach',
    outcomes: 'The receipts',
    source: 'Figures from our 2026 brand one-pager; a snapshot, not a live count.',
    top: 'Back to top',
    copyright: 'Chillchai Creations',
    viewProfile: 'Visit creator profile',
    enquirySubject: 'Chillchai Creations — project enquiry',
  },
  hero: {
    eyebrow: 'A CREATOR-LED SOCIAL MEDIA & PERSONAL BRANDING STUDIO',
    line1: 'Social media for brands.',
    line2: 'Personal brands',
    line3: 'for founders.',
    description: 'We manage social media for brands and build content-led personal brands for founders — from strategy and storytelling to production, publishing and growth.',
    primary: 'See what we do',
    secondary: 'Explore our work',
    note: 'Brewing stories.',
    foot: 'SOCIAL MEDIA MANAGEMENT · PERSONAL BRANDING',
    footRight: 'Brewing stories.',
  },
  services: {
    label: '01 / WHAT WE DO',
    title: 'Two core offerings.',
    italic: 'Clear, end-to-end support.',
    description: 'One wing for brands. One wing for founders. Both built around strong positioning, consistent content and audience trust.',
    wings: [
      {
        number: '01',
        audience: 'FOR BRANDS',
        name: 'Social Media Management',
        headline: 'Your social presence, managed end to end.',
        description: 'We turn your business goals into a clear content system, then run it consistently across strategy, creation, publishing and review.',
        includes: [
          'Brand positioning and content strategy',
          'Content pillars, formats and monthly calendars',
          'Scripting, shoot direction, design and editing',
          'Publishing and community management',
          'Performance reviews and ongoing refinement',
        ],
      },
      {
        number: '02',
        audience: 'FOR FOUNDERS & LEADERS',
        name: 'Personal Branding',
        headline: 'Build a voice people recognise and trust.',
        description: 'We shape your positioning and turn your ideas and experience into content that sounds like you and builds an audience over time.',
        includes: [
          'Positioning, audience and point of view',
          'Content pillars and recurring formats',
          'Scripts for LinkedIn, Instagram and short-form video',
          'Content production, publishing and consistency',
          'Community building and performance reviews',
        ],
      },
    ],
    shared: {
      label: 'ACROSS BOTH WINGS',
      text: 'Content strategy, storytelling, creator collaborations, recurring content IP and launch support — added when the brief calls for them.',
    },
  },
  about: {
    label: '02 / WHY CHILLCHAI',
    title: 'Creator experience.',
    italic: 'Applied to brands and founders.',
    body: 'We have built audiences, launched products and worked with brands ourselves. That firsthand experience shapes how we plan content, develop formats and make the work sustainable.',
    closing: 'Brewing stories.',
    items: [
      'Building creator audiences',
      'Developing recurring content series',
      'Working with brands',
      'Launching physical and digital products',
      'Managing creator collaborations',
    ],
  },
  proof: {
    label: 'CREATOR EXPERIENCE, IN NUMBERS.',
    items: [
      { value: '360K+', label: 'Combined followers & subscribers', note: 'Across Avishi, Kritarth and Protein Mummy. Platform totals; audiences may overlap.' },
      { value: '60+', label: 'Avishi’s brand collaborations', note: 'Creator collaborations, as reported in our one-pager.' },
      { value: '5', label: 'Products launched by Avishi', note: 'Across physical and digital products.' },
    ],
    note: 'Source: 2026 brand & offerings one-pager.',
  },
  work: {
    label: '03 / SELECTED WORK',
    title: 'Creator work.',
    italic: 'Built first-hand.',
    description: 'The audience-building experience behind the way we work with brands and founders.',
    projects: [
      {
        id: 'protein-mummy',
        name: 'Protein Mummy',
        category: 'MANAGED CREATOR ACCOUNT / PERSONAL BRANDING',
        theme: 'protein',
        image: '/assets/protein-mummy.webp',
        imageAlt: 'Protein Mummy',
        display: ['Series-led content.', 'Audience-led growth.'],
        stamp: 'MANAGED BY KRITARTH',
        summary: 'Building a recognisable creator identity through repeatable recipe formats.',
        context: 'Protein Mummy is a recipe-focused creator account managed by Kritarth. This work reflects hands-on experience building a creator identity and recurring content formats.',
        role: 'Creator account management, series-led content strategy, storytelling and recipe formats.',
        approach: ['Build a clear creator identity around recipe content.', 'Develop repeatable formats, including the Air Fryer series.', 'Use series-led storytelling to give viewers a reason to return.'],
        outcomes: [['213K', 'Instagram followers'], ['3.7M+', 'Monthly views'], ['10M+', 'Air Fryer series views']],
        note: 'The one-pager also names Pintola and OZiva as Protein Mummy partners.',
        links: [],
      },
      {
        id: 'avishi',
        name: 'Avishi’s creator ecosystem',
        category: 'OWNED CREATOR BRAND / PERSONAL BRANDING & PRODUCTS',
        theme: 'avishi',
        image: '/assets/avishi.webp',
        imageAlt: 'Avishi Mishra',
        display: ['Audience.', 'Collaborations. Products.'],
        stamp: 'OWNED CREATOR BRAND',
        summary: 'Firsthand experience turning content into an audience, brand collaborations and products.',
        context: 'Avishi’s own creator ecosystem is part of the operating experience behind Chillchai Creations.',
        role: 'Creator, product builder and founder of Chillchai Creations.',
        approach: ['Create across YouTube and Instagram.', 'Build experience through brand collaborations.', 'Extend the creator journey into physical and digital products.'],
        outcomes: [['89.7K', 'YouTube subscribers'], ['41.5K', 'Instagram followers'], ['5', 'Products launched']],
        note: '60+ brand collaborations reported in the supplied one-pager.',
        links: [{ label: '@avishimishh on Instagram', href: 'https://www.instagram.com/avishimishh/' }],
      },
    ],
  },
  team: {
    label: '04 / THE TEAM',
    title: 'The people behind',
    italic: 'Chillchai.',
    description: 'Creator experience and hands-on execution, brought together in one studio.',
    people: [
      {
        name: 'Avishi Mishra',
        initials: 'AM',
        image: '/assets/avishi.webp',
        imageAlt: 'Avishi Mishra',
        role: 'Founder',
        school: 'IIM Jammu',
        bio: 'Creator, product builder and founder. Brings firsthand experience across YouTube, Instagram, brand collaborations and product launches.',
        handle: '@avishimishh',
        href: 'https://www.instagram.com/avishimishh/',
      },
      {
        name: 'Kritarth Shuckla',
        initials: 'KS',
        image: '/assets/kritarth.webp',
        imageAlt: 'Kritarth Shuckla',
        role: 'Business Lead',
        school: 'IIT Bombay',
        bio: 'Creator and the operator behind Protein Mummy’s content strategy and management, with hands-on experience building recurring formats and audience growth.',
        handle: '@kriitarth',
        href: 'https://www.instagram.com/kriitarth/',
      },
    ],
  },
  process: {
    label: '05 / HOW WE WORK',
    title: 'From brief',
    italic: 'to publishing.',
    items: [
      ['Understand', 'Your brand, audience and business objective.'],
      ['Position', 'The story, point of view and content opportunities.'],
      ['Create and publish', 'Content, collaborations and campaigns, executed consistently.'],
      ['Review and improve', 'Performance, audience response and the next round of decisions.'],
    ],
  },
  contact: {
    label: 'CONTACT / START A PROJECT',
    title: 'Launching a brand soon?',
    italic: 'Building your personal brand?',
    subtitle: 'Let’s talk.',
    cta: 'Tell us about your project',
    email: 'avishimishra134@gmail.com',
    phone: '+91 96676 71258',
    whatsapp: 'https://wa.me/919667671258',
    whatsappLabel: 'Message us on WhatsApp',
    note: 'Tell us your goal, timeline and where you need support.',
  },
};

export type Project = typeof content.work.projects[number];
