// All visitor-facing copy, contact details and project records live here.
// Evidence: supplied offerings.pdf (2026 snapshot) and the user's website brief.
export const content = {
 brand: {name:'Chillchai', descriptor:'CREATIONS', tagline:'when life gives you lemons, make lemon tea.', logo:'/assets/logo.webp'},
 nav:[['Home','home'],['About','about'],['What We Do','services'],['Our Work','work'],['Contact','contact']],
 ui:{talk:"Let’s Talk",menu:'Menu',close:'Close',skip:'Skip to content',project:'Explore the project',back:'Back to all work',context:'The context',role:'Our role',approach:'The approach',outcomes:'The receipts',source:'Figures from our 2026 brand one-pager; a snapshot, not a live count.',top:'Back to top',copyright:'Chillchai Creations',viewProfile:'Visit creator profile',enquirySubject:'Let’s brew something together — project enquiry'},
 hero:{eyebrow:'A CREATOR-LED CONTENT & GROWTH STUDIO',line1:'Built by creators.',line2:'For brands that want',line3:'to be remembered.',description:'We turn stories into content, content into community, and community into lasting brand relationships.',primary:'Let’s brew something together',secondary:'Explore our work',note:'A little instinct.\nA lot of intention.',foot:'CONTENT · CREATORS · COMMUNITY',footRight:'Good stories. Lasting connections.'},
 about:{label:'01 / THE CHILLCHAI DIFFERENCE',title:'We don’t just make content.',italic:'We know what it takes to build an audience.',body:'We’ve built audiences, launched products and worked with brands ourselves. So we know the work behind the post — and what makes people come back.',closing:'Creator instinct. Operator follow-through.',items:['Building creator audiences','Developing recurring series','Working with brands','Launching our own products','Managing creator collaborations']},
 proof:{label:'A LITTLE CONTEXT. A FEW RECEIPTS.',items:[{value:'360K+',label:'Combined followers & subscribers',note:'Across Avishi, Kritarth and Protein Mummy. Platform totals; audiences may overlap.'},{value:'60+',label:'Avishi’s brand collaborations',note:'Creator collaborations, as reported in our one-pager.'},{value:'5',label:'Products launched by Avishi',note:'Across physical and digital products.'}],note:'Source: 2026 brand & offerings one-pager.'},
 services:{label:'02 / WHAT WE DO',title:'Good stories deserve',italic:'a proper plan.',description:'From the first idea to the next chapter. Here’s where we come in.',items:[['Content Strategy & Storytelling','Find the story only you can tell.','Audience research, positioning, content pillars, calendars and original ideas.'],['Creator & Influencer Marketing','The right people. A real connection.','Creator discovery, fitment, outreach, negotiation, campaign coordination and reporting.'],['Founder Personal Branding','Give the person behind the brand a voice.','Positioning, thought leadership, scripts, content production and audience building.'],['Social Media Management','Show up with something worth staying for.','Calendars, publishing, content execution, community engagement and performance reviews.'],['Content IP & Community','Make something people come back for.','Recurring series and recognisable formats that give an audience a reason to belong.']]},
 work:{label:'03 / SELECTED WORK',title:'Less pitch.',italic:'More proof.',description:'Our own creator journeys and the brands we’ve helped shape.',projects:[
 {id:'protein-mummy',name:'Protein Mummy',category:'CREATOR WORK / AUDIENCE BUILDING',theme:'protein',display:['A recipe for','coming back.'],stamp:'SERIES, NOT JUST POSTS',summary:'Turning recipe content into a recognisable creator identity.',context:'Protein Mummy is a recipe-focused creator account managed by Kritarth. This project reflects his hands-on experience building a creator identity and recurring content formats.',role:'Creator account management, series-led content strategy, storytelling and recipe formats.',approach:['Build a clear creator identity around recipe content.','Develop repeatable formats, including the Air Fryer series.','Use series-led storytelling to give viewers a reason to return.'],outcomes:[['213K','Instagram followers'],['3.7M+','Monthly views'],['10M+','Air Fryer series views']],note:'The one-pager also names Pintola and OZiva as Protein Mummy partners.',links:[]},
 {id:'capri-sports',name:'Capri Sports',category:'CLIENT WORK / SOCIAL & CREATOR MARKETING',theme:'capri',display:['From a blank page','to launch day.'],stamp:'STORY → SYSTEM → LAUNCH',summary:'A social content system and creator-collaboration engine, built from the ground up.',context:'A full social and content mandate, starting from zero social presence and supporting the launch of roll-on, sunscreen and moisturiser products.',role:'Social content strategy, creator collaboration infrastructure, content planning and launch execution.',approach:['Plan across three phases: brand and seeding, pre-launch, and revenue.','Organise creators into five archetype-based tiers.','Build barter and paid collaboration tracking.','Lead launch-related content for the hero products.'],outcomes:[],note:'Delivered an always-on content system and creator-collaboration infrastructure. No campaign performance or revenue figures are claimed.',links:[]},
 {id:'avishi',name:'Avishi’s creator ecosystem',category:'OWNED CREATOR BRAND / CONTENT & PRODUCTS',theme:'avishi',display:['An audience.','A world of possibility.'],stamp:'CREATE. CONNECT. BUILD.',summary:'Firsthand experience turning content into an audience, collaborations and products.',context:'Avishi’s own creator ecosystem is part of the experience behind Chillchai Creations.',role:'Creator, product builder and founder of Chillchai Creations.',approach:['Create across YouTube and Instagram.','Build experience through brand collaborations.','Extend the creator journey into physical and digital products.'],outcomes:[['89.7K','YouTube subscribers'],['41.5K','Instagram followers'],['5','Products launched']],note:'60+ brand collaborations reported in the supplied one-pager.',links:[{label:'@avishimishh on Instagram',href:'https://www.instagram.com/avishimishh/'}]}
 ]},
 team:{label:'04 / THE PEOPLE BEHIND THE BREW',title:'Creators first.',italic:'Operators always.',description:'Two perspectives. One shared belief: good content starts with understanding people.',people:[{name:'Avishi Mishra',initials:'AM',role:'Founder',school:'IIM Jammu',bio:'Building at the intersection of content, community and products. The creator perspective at the heart of Chillchai.',handle:'@avishimishh',href:'https://www.instagram.com/avishimishh/'},{name:'Kritarth Shuckla',initials:'KS',role:'Business Lead',school:'IIT Bombay',bio:'Creator and the operator behind Protein Mummy. Bringing audience-building experience to the business of content.',handle:'@kriitarth',href:'https://www.instagram.com/kriitarth/'}]},
 process:{label:'05 / HOW WE WORK',title:'A good brew',italic:'takes intention.',items:[['Understand','Your brand, your audience, and what you’re working towards.'],['Find the story','The positioning, creative direction and ideas worth making.'],['Make it real','Content, collaborations and campaigns. Thoughtfully executed.'],['Learn and improve','Look at what’s working. Listen to the audience. Make the next round better.']]},
 contact:{label:'YOUR NEXT CHAPTER STARTS HERE',title:'Got a story',italic:'worth telling?',subtitle:'Let’s brew it properly.',cta:'Start a conversation',email:'avishimishra134@gmail.com',phone:'+91 96676 71258',whatsapp:'https://wa.me/919667671258',whatsappLabel:'Say hello on WhatsApp',note:'Scoped to your project. Built around your story.'}
};
export type Project = typeof content.work.projects[number];
